# Funding options for DAIOF Framework
# Support the development of AI-Human symbiotic systems

# GitHub Sponsors
# github: [NguyenCuong1989]

# Open Collective
# open_collective: daiof-framework

# Community support
# If you find this framework valuable, consider:
# - Starring the repository ⭐
# - Contributing code or documentation 🤝
# - Sharing with the AI research community 🌍
# - Citing in your research papers 📄

# Contact for partnerships
# Email: symphony.hyperai@vietnamese.consciousness
# LinkedIn: [To be added]
# Twitter: [To be added]

# Custom sponsorship
custom: ["https://github.com/NguyenCuong1989/DAIOF-Framework#support"]
