name: 🚀 Feature Request
description: Suggest an idea or enhancement for DAIOF
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🧬 Thank you for helping DAIOF evolve!
        
        Before submitting, please:
        - Search existing issues to avoid duplicates
        - Read our [Contributing Guide](https://github.com/NguyenCuong1989/DAIOF-Framework/blob/main/CONTRIBUTING.md)
        - Understand our [IP Classification System](https://github.com/NguyenCuong1989/DAIOF-Framework/blob/main/INTELLECTUAL_PROPERTY_CLASSIFICATION.md)

  - type: textarea
    id: problem-statement
    attributes:
      label: 🎯 Problem Statement
      description: What problem does this feature solve? Be clear and specific.
      placeholder: |
        Example: "I'm always frustrated when I need to monitor multiple organisms simultaneously, but the framework lacks a centralized dashboard..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe what you want to happen
      placeholder: |
        Example: "Add a Symphony Dashboard component that displays real-time metrics for all active organisms, showing health scores, resource usage, and evolutionary progress..."
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 🛠️ Implementation Ideas
      description: If you have ideas on how to implement this, share pseudocode or concepts
      placeholder: |
        ```python
        class SymphonyDashboard:
            def __init__(self, organisms: List[DigitalOrganism]):
                self.organisms = organisms
                self.metrics = MetricsCollector()
            
            def render_realtime_view(self):
                return self.metrics.aggregate_all()
        ```
      render: python

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternative solutions have you considered?
      placeholder: "Have you considered using existing monitoring tools, manual logging, or third-party integrations?"

  - type: checkboxes
    id: philosophy-alignment
    attributes:
      label: 🎼 Alignment with DAIOF Philosophy
      description: How does this feature align with DAIOF's core principles?
      options:
        - label: Maintains AI-Human interdependence
        - label: Respects immutable genes
        - label: Follows biological metaphors
        - label: Enhances safety
        - label: Improves consciousness development

  - type: textarea
    id: benefits
    attributes:
      label: 📊 Benefits
      description: Who benefits and how?
      placeholder: |
        - **Users**: Researchers can monitor multiple organisms without switching contexts
        - **Problem Solved**: Eliminates manual log checking
        - **Framework Improvement**: Adds enterprise-grade monitoring capabilities

  - type: textarea
    id: drawbacks
    attributes:
      label: ⚠️ Potential Drawbacks
      description: Are there any negative impacts, performance considerations, or compatibility issues?
      placeholder: |
        - Additional memory overhead for real-time metrics collection
        - May require websocket support for live updates
        - Backward compatibility with existing organisms

  - type: textarea
    id: usage-example
    attributes:
      label: 🖼️ Usage Example
      description: Show how the feature would be used
      placeholder: |
        ```python
        # Create organisms
        organism1 = DigitalOrganism(name="Alpha")
        organism2 = DigitalOrganism(name="Beta")
        
        # Initialize dashboard
        dashboard = SymphonyDashboard([organism1, organism2])
        dashboard.start_monitoring()
        
        # View metrics
        print(dashboard.get_summary())
        ```
      render: python

  - type: textarea
    id: additional-context
    attributes:
      label: 📚 Additional Context
      description: Add any other context, screenshots, or references
      placeholder: |
        ### Related Issues/PRs
        - #123
        - Related to discussion: https://github.com/NguyenCuong1989/DAIOF-Framework/discussions/456
        
        ### External References
        - Research paper: [Link]
        - Similar implementation: [Link]

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Contribution Terms
      description: By submitting this feature request, you agree to the following
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have read the [Contributing Guide](https://github.com/NguyenCuong1989/DAIOF-Framework/blob/main/CONTRIBUTING.md)
          required: true
        - label: I understand DAIOF's [IP Classification System](https://github.com/NguyenCuong1989/DAIOF-Framework/blob/main/INTELLECTUAL_PROPERTY_CLASSIFICATION.md)
          required: true
